#!/usr/bin/env bash
#Script that:
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page) using curl,
#it must return a page that contains the string Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '48i rewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/learningdevops_404.html
sudo sed -i '37i \\terror_page 404 /learningdevops_404.html;\n\tlocation = /learningdevops_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\t}' /etc/nginx/sites-available/default
sudo service nginx restart
