#!/usr/bin/env bash
#configures a brand new Ubuntu machine
# shellcheck disable=SC2154

sudo apt-get -y update
sudo apt-get -y install nginx
var1=$HOSTNAME
var2="\n\tadd_header X-Served-By $var1;"
sudo sed -i "15i \\$var2" /etc/nginx/nginx.conf
sudo service nginx restart
