#!/usr/bin/env bash
#script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -uroot --all-databases --password="$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
