#!/usr/bin/env bash
#script that configures a server to listen on port 80

sudo rm /etc/nginx/sites-enable/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
sudo service nginx start