#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
echo "$$" > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/holbertonscript.pid; exit' SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
