#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i="1"
while [ $i -lt 101 ]
do
	if [ $((i%15)) -eq 0 ]
	then
		echo FizzBuzz
	elif [ $((i%3)) -eq 0 ]
	then
		echo Fizz
	elif [ $((i%5)) -eq 0 ]
	then
		echo Buzz
	else
		echo $i
	fi
	i=$((i+1))
done
